### ISSUE TITLE
Error in running WebJson.py

### ISSUE THREAD

**Issue by LingChian** [pcyuen98/python-intro#2]
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "C:\workspace\python-intro-main (1)\python-intro-main\src\JsonWeb.py", line 16, in <module>
    app.run()                                  # Standard Web Starter Instruction
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\web\application.py", line 360, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\web\wsgi.py", line 66, in runwsgi
    return httpserver.runsimple(func, server_addr)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\web\httpserver.py", line 176, in runsimple
    server.start()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\cheroot\server.py", line 1824, in start
    self.prepare()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\cheroot\server.py", line 1783, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 8080): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by pcyuen98** [comment]
It should be multiple web.py running on your host. 

On the eclipse, ensure the other instance is closed or restart the eclipse
