### ISSUE TITLE
JSON.web.py error (Duplicate) as issue #2

### ISSUE THREAD

**Issue by ooi19935566** [pcyuen98/python-intro#5]
import web

urls = (
     '/', 'index1'    # the index1 is mapping to the class name below on line 4

)

class index1:
    def GET(self):
        import Json                  # import something from GetMethod py File
        #return "Hello Chrome 123!"        # return simple message
        return Json.loadJson()

if __name__ == "__main__":                     # Standard Web Starter Instruction
    app = web.application(urls, globals())     # Mapping to line 4 'urls' variable to tell Python 
    app.run()    

No sure the error applier again 
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "D:\workspace\Python-Intro\src\Json\JsonWeb.py", line 16, in <module>
    app.run()                                  # Standard Web Starter Instruction                                 # Standard Web Starter Instruction                               # Standard Web Starter Instruction
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\web\application.py", line 360, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\web\wsgi.py", line 66, in runwsgi
    return httpserver.runsimple(func, server_addr)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\web\httpserver.py", line 176, in runsimple
    server.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\cheroot\server.py", line 1819, in start
    self.prepare()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\cheroot\server.py", line 1778, in prepare
    raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 8080): [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted)

**Comment by pcyuen98** [comment]
This seem duplicate error as below
https://github.com/pcyuen98/python-intro/issues/2

**Comment by ooi19935566** [comment]
okey understand so I need to click the stop button to stop it

**Comment by pcyuen98** [comment]
ya
